---
- name: install mariadb
  yum: name={{ item }} state=latest
  sudo: true
  register: mariadb_updated
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: write the mariadb config file
  template: src=mariadb_openstack.cnf.j2 dest=/etc/my.cnf.d/mariadb_openstack.cnf backup=yes
  sudo: true
  notify:
    - restart mariadb

- name: ensure mariadb is running
  sudo: true
  service: name=mariadb state=started enabled=yes

- name: Trigger handlers
  meta: flush_handlers

#  This can be executed non ineractively only in version 5.7.x
#- name: secure installation
#  sudo: true
#  command: mysql_secure_installation && touch /etc/mysql/mysql_secure_installation
#  args:
#    creates: /etc/mysql/mysql_secure_installation


# mysql_secure_installation

- name: delete anonymous MariaDB server user for {{ ansible_hostname }}
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1
    - "%"
  when: mariadb_updated.changed

- name: remove the MariaDB test database
  mysql_db: db=test state=absent
  when: mariadb_updated.changed

- name: DB setup for Keystone
  include: keystone-db.yml

- name: DB setup for Glance
  include: glance-db.yml

- name: DB setup for Nova
  include: nova-db.yml

- name: DB setup for Neutron
  include: neutron-db.yml

- name: DB setup for Cinder
  include: cinder-db.yml

- name: DB setup for Heat
  include: heat-db.yml

- name: restart openstack-db by handlers
  shell: echo 'Restarting openstack-db(mariadb)....'
  tags:
    - restart-components
  notify:
    - restart mariadb