---
- name: Create a new database with name 'neutron'
  mysql_db: name=neutron state=present

- name: create db user for neutron
  mysql_user:
    name: neutron
    password: "{{ os_dbs.neutron.password }}"
    host: "{{ item }}"
    state: present
    priv: "neutron.*:ALL"
  with_items: "{{ db_access_host }}"