---
- name: Create a new database with name 'nova'
  mysql_db: name=nova state=present

- name: create db user for nova
  mysql_user:
    name: nova
    password: "{{ os_dbs.nova.password }}"
    host: "{{ item }}"
    state: present
    priv: "nova.*:ALL"
  with_items: "{{ db_access_host }}"