---
- name: create glance_root
  file: path={{ glance_root }}/var/{{ item }} state=directory mode=0755
  sudo: true
  with_items:
    - lib

- name: install glance
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - glance
    - python-glanceclient

- name: write glance-api.conf file
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf backup=yes
  sudo: true
  register: write_glance_api_conf
  notify:
    - populate glancedb
    - restart glance-api

- name: write glance-registry.conf file
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf backup=yes
  sudo: true
  notify:
    - populate glancedb
    - restart glance-registry

- name: copy glance files to another location
  shell: cp -r /var/lib/glance {{ glance_root }}/var/lib/glance && chown -R glance:glance {{ glance_root }}/var/lib/glance creates={{ glance_root }}/var/lib/glance
  sudo: true
  when: write_glance_api_conf.changed

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/glance/glance.sqlite state=absent


- name: Setup Glance entities
  include: glance-init.yml
