---
- name: Creates scripts
  file: path=~/scripts state=directory

- name: create keystone-entities
  template: src=scripts/keystone-init.sh.j2 dest=~/scripts/keystone-init.sh mode="u+x"
  register: keystone_entities

- name: execute keystone-entities
  shell: ~/scripts/keystone-init.sh
  when: keystone_entities.changed

- name: write admin-openrc.sh
  template: src=scripts/admin-openrc.sh.j2 dest=~/scripts/admin-openrc.sh mode="u+x"

- name: write demo-openrc.sh
  template: src=scripts/demo-openrc.sh.j2 dest=~/scripts/demo-openrc.sh mode="u+x"