---
- name: install keystone
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - keystone
    - python-keystoneclient

- name: write the keystone config file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf backup=yes
  sudo: true
  notify:
    - populate identitydb
    - restart keystone

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/keystone/keystone.db state=absent

- name: periodic task that purges expired tokens hourly
  sudo: true
  shell: crontab -l -u keystone 2>&1 | grep -q token_flush || echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' >> /var/spool/cron/crontabs/keystone
  changed_when: false

- name: Creates scripts
  file: path=~/scripts state=directory

- name: create keystone-entities
  template: src=scripts/keystone-init.sh.j2 dest=~/scripts/keystone-init.sh mode="u+x"
  register: keystone_entities

- name: execute keystone-entities
  shell: ~/scripts/keystone-init.sh
  when: keystone_entities.changed

- name: write admin-openrc.sh
  template: src=scripts/admin-openrc.sh.j2 dest=~/scripts/admin-openrc.sh mode="u+x"

- name: write demo-openrc.sh
  template: src=scripts/demo-openrc.sh.j2 dest=~/scripts/demo-openrc.sh mode="u+x"

- name: write shell profile
  template: src=profile.j2 dest=~/.profile