---
- name: install keystone
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - keystone
    - python-keystoneclient

- name: write the keystone config file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf backup=yes
  sudo: true
  notify:
    - populate identitydb
    - restart keystone

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/keystone/keystone.db state=absent

- name: periodic task that purges expired tokens hourly
  sudo: true
  shell: crontab -l -u keystone 2>&1 | grep -q token_flush || echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' >> /var/spool/cron/crontabs/keystone
  changed_when: false

- name: Creates scripts
  sudo: true
  file: path=/opt/scripts state=directory mode="a+x"

- name: write helper scripts
  sudo: true
  template: src=scripts/{{ item }}.j2 dest=/opt/scripts/{{ item }} mode="a+x"
  with_items:
    - admin-openrc.sh
    - demo-openrc.sh
    - keystone-helper.sh

- name: create keystone-entities
  sudo: true
  template: src=scripts/keystone-init.sh.j2 dest=/opt/scripts/keystone-init.sh mode="a+x"
  register: keystone_entities

- name: execute keystone-entities
  shell: /opt/scripts/keystone-init.sh
  when: keystone_entities.changed

- name: write shell profile
  template: src=profile.j2 dest=~/.profile

- name: restart keystone components by handlers
  shell: echo 'Restarting keystone components....'
  tags:
    - restart-components
  notify:
    - restart keystone