---
- name: install horizon
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - openstack-dashboard
    - libapache2-mod-wsgi
    - memcached
    - python-memcache
    - apache2

- name: write local_settings.py file
  template: src=local_settings.py.j2 dest=/etc/openstack-dashboard/local_settings.py backup=yes
  sudo: true
  notify:
    - restart horizon

- name: Trigger handlers
  meta: flush_handlers

- name: restart horizon components by handlers
  shell: echo 'Restarting horizon components....'
  tags:
    - restart-components
  notify:
    - restart horizon