---
- name: install horizon
  yum: name={{ item }} state=latest
  sudo: true
  with_items:
    - openstack-dashboard
    - httpd
    - mod_wsgi
    - memcached
    - python-memcached

- name: On RHEL and CentOS, configure SELinux to permit the web server to connect to OpenStack services
  sudo: true
  seboolean: name=httpd_can_network_connect state=yes persistent=yes

- name: Due to a packaging bug, the dashboard CSS fails to load properly. Run the following command to resolve this issue
  sudo: true
  file: path=/usr/share/openstack-dashboard/static state=directory recurse=yes owner=apache group=apache

- name: write local_settings.py file
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings backup=yes
  sudo: true
  notify:
    - restart horizon

- name: Trigger handlers
  meta: flush_handlers

- name: ensure horizon services are running
  sudo: true
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
    - memcached

- name: restart horizon components by handlers
  shell: echo 'Restarting horizon components....'
  tags:
    - restart-components
  notify:
    - restart horizon