---
- name: populate novadb
  sudo: true
  shell: su -s /bin/sh -c "nova-manage db sync" nova

- name: restart nova controller
  sudo: true
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy