---
- name: install qemu
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - qemu
  when: virt_type == 'qemu'

- name: install nova components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - nova-compute
    - sysfsutils

- name: write the nova config file
  template: src={{ item }}.j2 dest=/etc/nova/{{ item }} backup=yes
  sudo: true
  notify:
    - restart nova compute
  with_items:
    - nova.conf
    - nova-compute.conf

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/nova/nova.sqlite state=absent