---
- name: install nova components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient

