---
- name: install basic utilities
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - ntp
    - sysstat
    - tree
    - traceroute

- name: creates installed directory to keep track what has been installed already
  file: path={{ installed_dir }} state=directory
  sudo: true

- name: write hosts file
  template: src=hosts.j2 dest=/etc/hosts
  sudo: true
