---
- name: disable selinux
  sudo: true
  selinux: state=permissive policy=targeted

- name: install epel release repo
  yum: name=epel-release state=latest
  sudo: true

- name: install basic utilities
  yum: name={{ item }} state=latest
  sudo: true
  with_items:
    - ntp
    - sysstat
    - tree
    - traceroute
    - iperf
    - net-tools
    - which

- name: ensure ntpd is running
  sudo: true
  service: name=ntpd state=started enabled=yes

- name: install openstack kilo repo
  sudo: true
  yum: name=http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm state=present

- name: install openstack-selinux
  yum: name={{ item }} state=latest
  sudo: true
  with_items:
    - openstack-selinux

- name: creates installed directory to keep track what has already been installed
  file: path={{ installed_dir }} state=directory
  sudo: true

- name: install yum plugin versionlock
  yum: name=yum-plugin-versionlock state=latest
  sudo: true

- name: add python-urllib3,python-requests package specifier with version
  command: yum versionlock {{ item }}
  sudo: true
  with_items:
    - python-requests-2.7.0-6.el7.noarch
    - python-urllib3-1.10.4-1.20150503gita91975b.el7.noarch