---
- name: restart neutron server
  sudo: true
  service: name={{ item }} state=restarted
  with_items:
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-ovs-cleanup
  when: neutron_node

- name: restart neutron controller
  sudo: true
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - neutron-server
  when: neutron_controller