---
- name: restart neutron server
  sudo: true
  service: name={{ item }} state=restarted
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  when: neutron_node

- name: restart neutron controller
  sudo: true
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - neutron-server
  when: neutron_controller