---
- name: install cinder controller components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - cinder-api
    - cinder-scheduler
    - python-cinderclient

- name: Creates scripts
  sudo: true
  file: path=/opt/scripts state=directory mode="a+x"

- name: create cinder-entities
  sudo: true
  template: src=scripts/cinder-init.sh.j2 dest=/opt/scripts/cinder-init.sh mode="a+x"
  register: cinder_entities

- name: execute cinder-entities
  shell: /opt/scripts/cinder-init.sh
  when: cinder_entities.changed

- name: write the cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  sudo: true
  notify:
    - populate cinderdb
    - restart cinder controller

- name: Trigger handlers
  meta: flush_handlers

- name: restart cinder components by handlers
  shell: echo 'Restarting cinder components....'
  tags:
    - restart-components
  notify:
    - restart cinder controller