---
- name: install cinder controller components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - cinder-api
    - cinder-scheduler
    - python-cinderclient

- name: Creates scripts
  file: path=~/scripts state=directory

- name: create cinder-entities
  template: src=scripts/cinder-init.sh.j2 dest=~/scripts/cinder-init.sh mode="u+x"
  register: cinder_entities

- name: execute cinder-entities
  shell: ~/scripts/cinder-init.sh
  when: cinder_entities.changed

- name: write the cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  sudo: true
  notify:
    - populate cinderdb
    - restart cinder controller

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/cinder/cinder.sqlite state=absent