---
- name: ensure needed repositories are present
  command: apt-add-repository -y "{{ item }}"
  with_items:
      - cloud-archive:juno
  sudo: true
  changed_when: false

- name: Run the equivalent of "apt-get update" as a separate step
  apt: update_cache=yes
  sudo: true

- name: Update all packages to the latest version
  apt: upgrade=dist
  sudo: true

- name: register running kernel version
  command: uname -r
  changed_when: false
  register: running_kernel

- name: register installed kernel version
  shell: dpkg --get-selections  | grep "linux-image-[0-9]" | sort | tail -1 | awk '{print $1}' | sed "s/linux-image-//"
  register: installed_kernel
  changed_when: installed_kernel.stdout != running_kernel.stdout

- name: reboot if kernel version has changed
  include: reboot.yml
  when: installed_kernel.stdout != running_kernel.stdout
