- name: Provision Openstack
  hosts: all
  roles:
    - updates
    - common

- name: Provision Controller
  include: os-controller.yml

#- name: Provision Network
#  include: os-network.yml

- name: Provision Compute
  include: os-compute.yml