---
- name: install heat controller components
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine
    - python-heatclient

- name: Creates scripts
  sudo: true
  file: path=/opt/scripts state=directory mode="a+x"

- name: create heat-entities
  sudo: true
  template: src=scripts/heat-init.sh.j2 dest=/opt/scripts/heat-init.sh mode="a+x"
  register: heat_entities

- name: execute heat-entities
  shell: /opt/scripts/heat-init.sh
  when: heat_entities.changed

- name: write the heat config file
  template: src=heat.conf.j2 dest=/etc/heat/heat.conf backup=yes
  sudo: true
  notify:
    - populate heatdb
    - restart heat services

- name: Trigger handlers
  meta: flush_handlers

- name: remove unused sqlite database
  sudo: true
  file: path=/var/lib/heat/heat.sqlite state=absent